export const FETCH_STOCK_DATA_PENDING = 'FETCH_STOCK_DATA_PENDING';
export const FETCH_STOCK_DATA_SUCCESS = 'FETCH_STOCK_DATA_SUCCESS';
export const FETCH_STOCK_DATA_ERROR = 'FETCH_STOCK_DATA_ERROR';

export const ADD_POSITION_PENDING = 'ADD_POSITION_PENDING';
export const ADD_POSITION_ERROR = 'ADD_POSITION_ERROR';
export const ADD_POSITION_SUCCESS = 'ADD_POSITION_SUCCESS';

export const REMOVE_POSITION_PENDING = 'REMOVE_POSITION_PENDING';
export const REMOVE_POSITION_ERROR = 'REMOVE_POSITION_ERROR';
export const REMOVE_POSITION_SUCCESS = 'REMOVE_POSITION_SUCCESS';